"""user storage added

Revision ID: 06c3fcfe861f
Revises: b31d8e4d99e6
Create Date: 2025-12-29 14:59:17.186460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c3fcfe861f'
down_revision: Union[str, None] = 'b31d8e4d99e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_used', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_used')
    # ### end Alembic commands ###

