"""add failed enum for file

Revision ID: b31d8e4d99e6
Revises: 52211d6c1ebf
Create Date: 2025-12-28 07:50:57.612065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31d8e4d99e6'
down_revision: Union[str, None] = '52211d6c1ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE filestatus ADD VALUE IF NOT EXISTS 'FAILED'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

